name: CICD

on:
  push: 
    branches: 
    - '**'
    - 'main'
    - 'develop'
    
  release:
    types: 
     - created
env:
  IMAGE_NAME: fbiopereira/movies-api-pos-tech-fiap
  IMAGE_VERSION: ${{github.sha}}  

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set Version Variable
        shell: bash
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "IIMAGE_VERSION=main-${{github.sha}}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "develop" ]]; then
            echo "IIMAGE_VERSION=dev-${{github.sha}}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == release/* ]]; then
            echo "IIMAGE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          fi

        
      - name: EXIBE VERSION
        run: echo ${{env.IIMAGE_VERSION}} 
    
      - name: Code Checkout
        uses: actions/checkout@v4.1.1    
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}   

      - name: Build and push docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          build-args: |
            "APP_VERSION=${{env.IMAGE_VERSION}}"
            
          file: Dockerfile
          push: true       
          tags: |            
            ${{env.IMAGE_NAME}}:latest
            ${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
            
           
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.5
        with:      
          creds: ${{secrets.AZURE_CREDENTIALS}}
      
           

            
          
