name: CICD

on:
  push:
    branches: 
      - "*/*" 
  pull_request:
    branches: 
      - "main" 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .    
          load: true       
          tags: fbiopereira/movies-api-fiap:latest
          push: true           
            
          